/*

CREATED BY : ANDRE CARLOS
DATE OF CREATION : JUL/2017
SUMMARY:
This script is for a personal review of database programming and administration.
This can by used by anyone who wants study database technology. Future scripts will
include PL/SQL and NoSQL programming.

contato@andrecarlos.com.br
SAO PAULO - BRAZIL

*/

USE [master]
GO

/****** Object:  Database [GuiaPratico]    Script Date: 22/07/2017 16:51:36 ******/
CREATE DATABASE [GuiaPratico]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GuiaPratico', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.NOTESQL2016\MSSQL\DATA\GuiaPratico.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GuiaPratico_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.NOTESQL2016\MSSQL\DATA\GuiaPratico_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GuiaPratico] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GuiaPratico].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GuiaPratico] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GuiaPratico] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GuiaPratico] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GuiaPratico] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GuiaPratico] SET ARITHABORT OFF 
GO

ALTER DATABASE [GuiaPratico] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GuiaPratico] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GuiaPratico] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GuiaPratico] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GuiaPratico] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GuiaPratico] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GuiaPratico] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GuiaPratico] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GuiaPratico] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GuiaPratico] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GuiaPratico] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GuiaPratico] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GuiaPratico] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GuiaPratico] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GuiaPratico] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GuiaPratico] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GuiaPratico] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GuiaPratico] SET RECOVERY FULL 
GO

ALTER DATABASE [GuiaPratico] SET  MULTI_USER 
GO

ALTER DATABASE [GuiaPratico] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GuiaPratico] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GuiaPratico] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GuiaPratico] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GuiaPratico] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GuiaPratico] SET QUERY_STORE = OFF
GO

USE [GuiaPratico]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GuiaPratico] SET  READ_WRITE 
GO

